# Generated by Django 4.2.27 on 2025-12-19 19:22

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': [django.db.models.functions.text.Lower('author__username')]},
        ),
    ]
